export const Spacing = {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    screenPadding: 16,
    cardRadius: 12,
    buttonRadius: 8,
    pillRadius: 24,
    inputHeight: 48,
    tabBarHeight: 64,
    fabSize: 56,
};
