export interface University {
  name: string;
  shortName?: string;
  state: string;
  type: 'federal' | 'state' | 'private';
}

export const NIGERIAN_UNIVERSITIES: University[] = [
  // ── FEDERAL UNIVERSITIES (Source: NUC official list, March 2026) ──
  { name: 'Abubakar Tafawa Balewa University', shortName: 'ATBU', state: 'Bauchi', type: 'federal' },
  { name: 'Admiralty University Ibusa', shortName: 'ADUN', state: 'Delta', type: 'federal' },
  { name: 'African Aviation and Aerospace University', shortName: 'AAAU', state: 'FCT', type: 'federal' },
  { name: 'Ahmadu Bello University', shortName: 'ABU', state: 'Kaduna', type: 'federal' },
  { name: 'Air Force Institute of Technology', shortName: 'AFIT', state: 'Kaduna', type: 'federal' },
  { name: 'Adeyemi Federal University of Education', state: 'Ondo', type: 'federal' },
  { name: 'Alex Ekwueme University Ndufu-Alike', shortName: 'FUNAI', state: 'Ebonyi', type: 'federal' },
  { name: 'Alvan Ikoku Federal University of Education', state: 'Imo', type: 'federal' },
  { name: 'Bayero University Kano', shortName: 'BUK', state: 'Kano', type: 'federal' },
  { name: 'David Nweze Umahi Federal University of Medical Sciences', shortName: 'KDUMS', state: 'Ebonyi', type: 'federal' },
  { name: 'Federal University Birnin Kebbi', shortName: 'FUBK', state: 'Kebbi', type: 'federal' },
  { name: 'Federal University Dutse', shortName: 'FUD', state: 'Jigawa', type: 'federal' },
  { name: 'Federal University Dutsin-Ma', shortName: 'FUDMA', state: 'Katsina', type: 'federal' },
  { name: 'Federal University Gashua', shortName: 'FUGASHUA', state: 'Yobe', type: 'federal' },
  { name: 'Federal University Gusau', shortName: 'FUGUS', state: 'Zamfara', type: 'federal' },
  { name: 'Federal University Kashere', shortName: 'FUKASHERE', state: 'Gombe', type: 'federal' },
  { name: 'Federal University Lafia', shortName: 'FULAFIA', state: 'Nasarawa', type: 'federal' },
  { name: 'Federal University Lokoja', shortName: 'FULOKOJA', state: 'Kogi', type: 'federal' },
  { name: 'Federal University Otuoke', shortName: 'FUOTUOKE', state: 'Bayelsa', type: 'federal' },
  { name: 'Federal University Oye-Ekiti', shortName: 'FUOYE', state: 'Ekiti', type: 'federal' },
  { name: 'Federal University Wukari', shortName: 'FUWUKARI', state: 'Taraba', type: 'federal' },
  { name: 'Federal University of Agriculture Abeokuta', shortName: 'FUNAAB', state: 'Ogun', type: 'federal' },
  { name: 'Federal University of Agriculture Bassam-Biri', state: 'Bayelsa', type: 'federal' },
  { name: 'Federal University of Agriculture Mubi', state: 'Adamawa', type: 'federal' },
  { name: 'Federal University of Agriculture Zuru', shortName: 'FUAZ', state: 'Kebbi', type: 'federal' },
  { name: 'Federal University of Agriculture and Technology Okeho', state: 'Oyo', type: 'federal' },
  { name: 'Federal University of Allied Health Sciences Enugu', shortName: 'FUAHSE', state: 'Enugu', type: 'federal' },
  { name: 'Federal University of Applied Sciences Kachia', state: 'Kaduna', type: 'federal' },
  { name: 'Federal University of Education Kontagora', state: 'Niger', type: 'federal' },
  { name: 'Federal University of Education Pankshin', state: 'Plateau', type: 'federal' },
  { name: 'Federal University of Education Zaria', state: 'Kaduna', type: 'federal' },
  { name: 'Federal University of Environment and Technology Tai Town', state: 'Rivers', type: 'federal' },
  { name: 'Federal University of Health Science and Technology Tsafe', state: 'Zamfara', type: 'federal' },
  { name: 'Federal University of Health Sciences Azare', state: 'Bauchi', type: 'federal' },
  { name: 'Federal University of Health Sciences Ila-Orangun', state: 'Osun', type: 'federal' },
  { name: 'Federal University of Health Sciences Katsina', state: 'Katsina', type: 'federal' },
  { name: 'Federal University of Health Sciences Kwale', state: 'Delta', type: 'federal' },
  { name: 'Federal University of Health Sciences Otukpo', state: 'Benue', type: 'federal' },
  { name: 'Federal University of Medicine and Medical Sciences Abeokuta', shortName: 'FUMMSA', state: 'Ogun', type: 'federal' },
  { name: 'Federal University of Petroleum Resources Effurun', shortName: 'FUPRE', state: 'Delta', type: 'federal' },
  { name: 'Federal University of Technology Akure', shortName: 'FUTA', state: 'Ondo', type: 'federal' },
  { name: 'Federal University of Technology Babura', shortName: 'FUTB', state: 'Jigawa', type: 'federal' },
  { name: 'Federal University of Technology Ikot Abasi', state: 'Akwa Ibom', type: 'federal' },
  { name: 'Federal University of Technology Minna', shortName: 'FUTMinna', state: 'Niger', type: 'federal' },
  { name: 'Federal University of Technology Owerri', shortName: 'FUTO', state: 'Imo', type: 'federal' },
  { name: 'Federal University of Technology and Environmental Studies Iyin-Ekiti', state: 'Ekiti', type: 'federal' },
  { name: 'Federal University of Transportation Daura', shortName: 'FUTD', state: 'Katsina', type: 'federal' },
  { name: 'Joseph Sarwuan Tarka University Makurdi', shortName: 'FUAM', state: 'Benue', type: 'federal' },
  { name: 'Michael Okpara University of Agriculture Umudike', shortName: 'MOUAU', state: 'Abia', type: 'federal' },
  { name: 'Modibbo Adama University of Technology Yola', shortName: 'MAUTECH', state: 'Adamawa', type: 'federal' },
  { name: 'National Open University of Nigeria', shortName: 'NOUN', state: 'FCT', type: 'federal' },
  { name: 'National University of Science and Technology Abuja', state: 'FCT', type: 'federal' },
  { name: 'Nigeria Police Academy Wudil', shortName: 'POLAC', state: 'Kano', type: 'federal' },
  { name: 'Nigerian Army University Biu', shortName: 'NAUB', state: 'Borno', type: 'federal' },
  { name: 'Nigerian Defence Academy', shortName: 'NDA', state: 'Kaduna', type: 'federal' },
  { name: 'Nigerian Maritime University Okerenkoko', shortName: 'NMU', state: 'Delta', type: 'federal' },
  { name: 'Nnamdi Azikiwe University', shortName: 'UNIZIK', state: 'Anambra', type: 'federal' },
  { name: 'Obafemi Awolowo University', shortName: 'OAU', state: 'Osun', type: 'federal' },
  { name: 'Tai Solarin Federal University of Education Ijagun', state: 'Ogun', type: 'federal' },
  { name: 'University of Abuja', shortName: 'UNIABUJA', state: 'FCT', type: 'federal' },
  { name: 'University of Agriculture and Developmental Studies Iragbuji', state: 'Osun', type: 'federal' },
  { name: 'University of Benin', shortName: 'UNIBEN', state: 'Edo', type: 'federal' },
  { name: 'University of Calabar', shortName: 'UNICAL', state: 'Cross River', type: 'federal' },
  { name: 'University of Ibadan', shortName: 'UI', state: 'Oyo', type: 'federal' },
  { name: 'University of Ilorin', shortName: 'UNILORIN', state: 'Kwara', type: 'federal' },
  { name: 'University of Jos', shortName: 'UNIJOS', state: 'Plateau', type: 'federal' },
  { name: 'University of Lagos', shortName: 'UNILAG', state: 'Lagos', type: 'federal' },
  { name: 'University of Maiduguri', shortName: 'UNIMAID', state: 'Borno', type: 'federal' },
  { name: 'University of Maritime Studies Oron', state: 'Akwa Ibom', type: 'federal' },
  { name: 'University of Nigeria Nsukka', shortName: 'UNN', state: 'Enugu', type: 'federal' },
  { name: 'University of Port Harcourt', shortName: 'UNIPORT', state: 'Rivers', type: 'federal' },
  { name: 'University of Uyo', shortName: 'UNIUYO', state: 'Akwa Ibom', type: 'federal' },
  { name: 'Usmanu Danfodiyo University', shortName: 'UDUS', state: 'Sokoto', type: 'federal' },
  { name: 'Yusuf Maitama Sule Federal University of Education Kano', state: 'Kano', type: 'federal' },

  // ── STATE UNIVERSITIES (Source: NUC official list, March 2026) ──
  { name: 'Abia State University', shortName: 'ABSU', state: 'Abia', type: 'state' },
  { name: 'AbdulKadir Kure University Minna', state: 'Niger', type: 'state' },
  { name: 'Abdulsalam Abubakar University of Agriculture and Climate Action', state: 'Niger', type: 'state' },
  { name: 'Adekunle Ajasin University', shortName: 'AAUA', state: 'Ondo', type: 'state' },
  { name: 'Adamawa State University Mubi', shortName: 'ADSU', state: 'Adamawa', type: 'state' },
  { name: 'Akwa Ibom State University', shortName: 'AKSU', state: 'Akwa Ibom', type: 'state' },
  { name: 'Aliko Dangote University of Science and Technology Wudil', shortName: 'KUST', state: 'Kano', type: 'state' },
  { name: 'Ambrose Alli University Ekpoma', shortName: 'AAU', state: 'Edo', type: 'state' },
  { name: 'Bamidele Olumilua University of Science and Technology Ikere', shortName: 'BOUESTI', state: 'Ekiti', type: 'state' },
  { name: 'Bauchi State University Gadau', shortName: 'BASUG', state: 'Bauchi', type: 'state' },
  { name: 'Bayelsa Medical University', shortName: 'BMU', state: 'Bayelsa', type: 'state' },
  { name: 'Benue State University of Agriculture Science and Technology', state: 'Benue', type: 'state' },
  { name: 'Chukwuemeka Odumegwu Ojukwu University', shortName: 'COOU', state: 'Anambra', type: 'state' },
  { name: 'Confluence University of Science and Technology Osara', shortName: 'CUSTECH', state: 'Kogi', type: 'state' },
  { name: 'Cross River University of Education and Entrepreneurship', state: 'Cross River', type: 'state' },
  { name: 'Delta State University Abraka', shortName: 'DELSU', state: 'Delta', type: 'state' },
  { name: 'Delta University of Science and Technology Ozoro', shortName: 'DSUST', state: 'Delta', type: 'state' },
  { name: 'Dennis Osadebe University Asaba', shortName: 'DOU', state: 'Delta', type: 'state' },
  { name: 'Ebonyi State University', shortName: 'EBSU', state: 'Ebonyi', type: 'state' },
  { name: 'Ebonyi State University of ICT Science and Technology', state: 'Ebonyi', type: 'state' },
  { name: 'Edo State University Iyamho', state: 'Edo', type: 'state' },
  { name: 'Ekiti State University', shortName: 'EKSU', state: 'Ekiti', type: 'state' },
  { name: 'Emanuel Alayande University of Education Oyo', state: 'Oyo', type: 'state' },
  { name: 'Enugu State University of Science and Technology', shortName: 'ESUT', state: 'Enugu', type: 'state' },
  { name: 'First Technical University Ibadan', shortName: 'TECH-U', state: 'Oyo', type: 'state' },
  { name: 'Gombe State University', shortName: 'GSU', state: 'Gombe', type: 'state' },
  { name: 'Ibrahim Badamasi Babangida University Lapai', shortName: 'IBBU', state: 'Niger', type: 'state' },
  { name: 'Ignatius Ajuru University of Education', shortName: 'IAUE', state: 'Rivers', type: 'state' },
  { name: 'Imo State University', shortName: 'IMSU', state: 'Imo', type: 'state' },
  { name: 'Kaduna State University', shortName: 'KASU', state: 'Kaduna', type: 'state' },
  { name: 'Kashim Ibrahim University Maiduguri', state: 'Borno', type: 'state' },
  { name: 'Kebbi State University of Science and Technology', shortName: 'KSUSTA', state: 'Kebbi', type: 'state' },
  { name: 'Kingsley Ozumba Mbadiwe University', shortName: 'KOMU', state: 'Imo', type: 'state' },
  { name: 'Kogi State University Kabba', state: 'Kogi', type: 'state' },
  { name: 'Kwara State University', shortName: 'KWASU', state: 'Kwara', type: 'state' },
  { name: 'Kwara State University of Education', state: 'Kwara', type: 'state' },
  { name: 'Ladoke Akintola University of Technology', shortName: 'LAUTECH', state: 'Oyo', type: 'state' },
  { name: 'Lagos State University', shortName: 'LASU', state: 'Lagos', type: 'state' },
  { name: 'Lagos State University of Education', state: 'Lagos', type: 'state' },
  { name: 'Lagos State University of Science and Technology', state: 'Lagos', type: 'state' },
  { name: 'Moshood Abiola University of Science and Technology', state: 'Ogun', type: 'state' },
  { name: 'Nasarawa State University Keffi', shortName: 'NSUK', state: 'Nasarawa', type: 'state' },
  { name: 'Niger Delta University Yenagoa', shortName: 'NDU', state: 'Bayelsa', type: 'state' },
  { name: 'Northwest University Kano', shortName: 'NWU', state: 'Kano', type: 'state' },
  { name: 'Olabisi Onabanjo University', shortName: 'OOU', state: 'Ogun', type: 'state' },
  { name: 'Olusegun Agagu University of Science and Technology', shortName: 'OSUSTECH', state: 'Ondo', type: 'state' },
  { name: 'Osun State University', shortName: 'UNIOSUN', state: 'Osun', type: 'state' },
  { name: 'Plateau State University Bokkos', shortName: 'PLASU', state: 'Plateau', type: 'state' },
  { name: 'Prince Abubakar Audu University Anyigba', state: 'Kogi', type: 'state' },
  { name: 'Rev. Fr. Moses Orshio Adasu University Makurdi', shortName: 'BSUM', state: 'Benue', type: 'state' },
  { name: 'Rivers State University', shortName: 'RSU', state: 'Rivers', type: 'state' },
  { name: 'Shehu Shagari University of Education Sokoto', state: 'Sokoto', type: 'state' },
  { name: 'Sokoto State University', shortName: 'SSU', state: 'Sokoto', type: 'state' },
  { name: 'State University of Medical and Applied Sciences Igbo-Eno', state: 'Enugu', type: 'state' },
  { name: 'Sule Lamido University Kafin Hausa', shortName: 'SLU', state: 'Jigawa', type: 'state' },
  { name: 'Taraba State University', shortName: 'TASU', state: 'Taraba', type: 'state' },
  { name: "Umar Musa Yar'adua University Katsina", shortName: 'UMYU', state: 'Katsina', type: 'state' },
  { name: 'University of Africa Toru-Orua', shortName: 'UAT', state: 'Bayelsa', type: 'state' },
  { name: 'University of Agriculture and Environmental Sciences Umuagwo', shortName: 'UAES', state: 'Imo', type: 'state' },
  { name: 'University of Aeronautics and Aerospace Engineering Ezza', state: 'Ebonyi', type: 'state' },
  { name: 'University of Cross River State', shortName: 'CRUTECH', state: 'Cross River', type: 'state' },
  { name: 'University of Delta Agbor', shortName: 'UNIDEL', state: 'Delta', type: 'state' },
  { name: 'University of Ilesa', state: 'Osun', type: 'state' },
  { name: 'University of Innovation Science and Technology Omuma', state: 'Imo', type: 'state' },
  { name: 'University of Medical Sciences Ondo City', shortName: 'UNIMED', state: 'Ondo', type: 'state' },
  { name: 'Yobe State University', shortName: 'YSU', state: 'Yobe', type: 'state' },
  { name: 'Zamfara State University', shortName: 'ZASU', state: 'Zamfara', type: 'state' },

  // ── PRIVATE UNIVERSITIES (Source: NUC official list, March 2026) ──
  { name: 'Achievers University Owo', shortName: 'AU', state: 'Ondo', type: 'private' },
  { name: 'Adeleke University Ede', state: 'Osun', type: 'private' },
  { name: 'Afe Babalola University', shortName: 'ABUAD', state: 'Ekiti', type: 'private' },
  { name: 'African University of Science and Technology', shortName: 'AUST', state: 'FCT', type: 'private' },
  { name: 'African University of Economics', state: 'FCT', type: 'private' },
  { name: 'Ahman Pategi University', state: 'Kwara', type: 'private' },
  { name: 'Ajayi Crowther University', shortName: 'ACU', state: 'Oyo', type: 'private' },
  { name: 'Al-Ansar University Maiduguri', state: 'Borno', type: 'private' },
  { name: 'Al-Bayan University Ankpa', state: 'Kogi', type: 'private' },
  { name: 'Al-Hikmah University', state: 'Kwara', type: 'private' },
  { name: 'Al-Istiqama University Sumaila', state: 'Kano', type: 'private' },
  { name: 'Al-Muhibbah Open University', state: 'FCT', type: 'private' },
  { name: 'Al-Qalam University Katsina', state: 'Katsina', type: 'private' },
  { name: 'Aletheia University Ago-Iwoye', state: 'Ogun', type: 'private' },
  { name: 'Amadeus University Amizi', state: 'Abia', type: 'private' },
  { name: 'American Open University Abeokuta', state: 'Ogun', type: 'private' },
  { name: 'American University of Nigeria', shortName: 'AUN', state: 'Adamawa', type: 'private' },
  { name: 'Anan University Kwall', state: 'Plateau', type: 'private' },
  { name: 'Anchor University Lagos', state: 'Lagos', type: 'private' },
  { name: 'Arthur Jarvis University Akpoyubo', state: 'Cross River', type: 'private' },
  { name: 'Atiba University Oyo', state: 'Oyo', type: 'private' },
  { name: 'Augustine University', state: 'Lagos', type: 'private' },
  { name: 'Ave Maria University Piyanko', state: 'Nasarawa', type: 'private' },
  { name: 'Azman University Kano', state: 'Kano', type: 'private' },
  { name: 'Babcock University', state: 'Ogun', type: 'private' },
  { name: 'Baba Ahmed University Kano', state: 'Kano', type: 'private' },
  { name: 'Baze University', state: 'FCT', type: 'private' },
  { name: 'Bells University of Technology', shortName: 'BELLS', state: 'Ogun', type: 'private' },
  { name: 'Benson Idahosa University', shortName: 'BIU', state: 'Edo', type: 'private' },
  { name: 'Bingham University New Karu', state: 'Nasarawa', type: 'private' },
  { name: 'Bowen University Iwo', state: 'Osun', type: 'private' },
  { name: 'British Canadian University Obufu', state: 'Cross River', type: 'private' },
  { name: 'Caleb University', state: 'Lagos', type: 'private' },
  { name: 'Calvin Foundation University', state: 'Kogi', type: 'private' },
  { name: 'Canadian University of Nigeria', state: 'FCT', type: 'private' },
  { name: 'Capital City University Kano', shortName: 'CCUK', state: 'Kano', type: 'private' },
  { name: 'Caritas University Enugu', state: 'Enugu', type: 'private' },
  { name: 'Chrisland University', state: 'Ogun', type: 'private' },
  { name: 'Christopher University Mowe', state: 'Ogun', type: 'private' },
  { name: 'Claretian University of Nigeria Nekede', state: 'Imo', type: 'private' },
  { name: 'Clifford University Owerrinta', state: 'Abia', type: 'private' },
  { name: 'Coal City University Enugu', shortName: 'CCU', state: 'Enugu', type: 'private' },
  { name: 'College of Petroleum and Energy Studies Kaduna', state: 'Kaduna', type: 'private' },
  { name: 'Cosmopolitan University Abuja', state: 'FCT', type: 'private' },
  { name: 'Covenant University Ota', shortName: 'CU', state: 'Ogun', type: 'private' },
  { name: 'Crawford University Igbesa', state: 'Ogun', type: 'private' },
  { name: 'Crescent University', state: 'Ogun', type: 'private' },
  { name: 'Dominican University Ibadan', state: 'Oyo', type: 'private' },
  { name: 'Dominion University Ibadan', state: 'Oyo', type: 'private' },
  { name: 'Edusoko University Bida', state: 'Niger', type: 'private' },
  { name: 'Edwin Clark University Kaigbodo', state: 'Delta', type: 'private' },
  { name: 'Eko University of Medical and Health Sciences', state: 'Lagos', type: 'private' },
  { name: 'El-Amin University Minna', state: 'Niger', type: 'private' },
  { name: 'Elizade University', state: 'Ondo', type: 'private' },
  { name: 'Elrazi Medical University Kano', state: 'Kano', type: 'private' },
  { name: 'Eranova University Abuja', state: 'FCT', type: 'private' },
  { name: 'European University of Nigeria Duboyi', state: 'FCT', type: 'private' },
  { name: 'Evangel University Akaeze', state: 'Ebonyi', type: 'private' },
  { name: 'Fountain University Oshogbo', state: 'Osun', type: 'private' },
  { name: 'Franco British International University Kaduna', shortName: 'FBIU', state: 'Kaduna', type: 'private' },
  { name: 'Gerar University of Medical Science Imope Ijebu', state: 'Ogun', type: 'private' },
  { name: 'Glorious Vision University Ogwa', state: 'Edo', type: 'private' },
  { name: 'Godfrey Okoye University Ugwuomu-Nike', shortName: 'GOUNI', state: 'Enugu', type: 'private' },
  { name: 'Greenfield University Kaduna', state: 'Kaduna', type: 'private' },
  { name: 'Greenland University Jalingo', state: 'Taraba', type: 'private' },
  { name: 'Gregory University Uturu', state: 'Abia', type: 'private' },
  { name: 'Hallmark University Ijebi Itele', state: 'Ogun', type: 'private' },
  { name: 'Havilla University Nde-Ikom', state: 'Cross River', type: 'private' },
  { name: 'Hensard University Toru-Orua', state: 'Bayelsa', type: 'private' },
  { name: 'Hezekiah University Umudi', state: 'Imo', type: 'private' },
  { name: 'Hillside University of Science and Technology Okemisi', shortName: 'HUST', state: 'Ekiti', type: 'private' },
  { name: 'Huda University Gusau', state: 'Zamfara', type: 'private' },
  { name: 'Iconic Open University Sokoto', state: 'Sokoto', type: 'private' },
  { name: 'Igbinedion University Okada', shortName: 'IUO', state: 'Edo', type: 'private' },
  { name: 'Isaac Balami University of Aeronautics and Management', state: 'Lagos', type: 'private' },
  { name: 'James Hope University Lagos', shortName: 'JHU', state: 'Lagos', type: 'private' },
  { name: 'JEFAP University Suleja', state: 'Niger', type: 'private' },
  { name: 'Jewel University Gombe', state: 'Gombe', type: 'private' },
  { name: 'Jimoh Babalola University Ilorin', state: 'Kwara', type: 'private' },
  { name: 'Joseph Ayo Babalola University', shortName: 'JABU', state: 'Osun', type: 'private' },
  { name: 'Karl-Kumm University Vom', state: 'Plateau', type: 'private' },
  { name: 'Kevin Eze University Mgbowo', state: 'Enugu', type: 'private' },
  { name: 'Khadija University Majia', state: 'Jigawa', type: 'private' },
  { name: 'Khalifa Isiyaku Rabiu University Kano', state: 'Kano', type: 'private' },
  { name: 'Kings University Ode Omu', state: 'Osun', type: 'private' },
  { name: 'Kola Daisi University Ibadan', state: 'Oyo', type: 'private' },
  { name: 'Kwararafa University Wukari', state: 'Taraba', type: 'private' },
  { name: 'Landmark University Omu-Aran', state: 'Kwara', type: 'private' },
  { name: 'Lead City University Ibadan', state: 'Oyo', type: 'private' },
  { name: 'Leadership University Abuja', state: 'FCT', type: 'private' },
  { name: 'Legacy University Okija', state: 'Anambra', type: 'private' },
  { name: 'Lens University Ilemona', state: 'Kwara', type: 'private' },
  { name: 'Lighthouse University Evbobanosa', state: 'Edo', type: 'private' },
  { name: 'Lux Mundi University Umuahia', state: 'Abia', type: 'private' },
  { name: 'Madonna University Okija', state: 'Anambra', type: 'private' },
  { name: 'Maduka University Ekwegbe', state: 'Enugu', type: 'private' },
  { name: 'Maranatha University Lagos', state: 'Lagos', type: 'private' },
  { name: 'Margaret Lawrence University Umunede', state: 'Delta', type: 'private' },
  { name: 'Maryam Abacha American University of Nigeria', shortName: 'MAAUN', state: 'Kano', type: 'private' },
  { name: 'Mcpherson University Seriki Sotayo', shortName: 'MCU', state: 'Ogun', type: 'private' },
  { name: 'Mewar International University Masaka', shortName: 'MIU', state: 'Nasarawa', type: 'private' },
  { name: 'Michael and Cecilia Ibru University', shortName: 'MCIU', state: 'Delta', type: 'private' },
  { name: 'Minaret University Ikirun', state: 'Osun', type: 'private' },
  { name: 'Miva Open University', state: 'FCT', type: 'private' },
  { name: 'Monarch University Iyesi-Ota', state: 'Ogun', type: 'private' },
  { name: 'Mountain Top University', shortName: 'MTU', state: 'Ogun', type: 'private' },
  { name: 'Mudiame University Irrua', state: 'Edo', type: 'private' },
  { name: 'Muhammad Kamalud University Kwara', state: 'Kwara', type: 'private' },
  { name: 'New City University Ayetoro', state: 'Ogun', type: 'private' },
  { name: 'Newgate University Minna', state: 'Niger', type: 'private' },
  { name: 'Nigerian British University Asa', shortName: 'NBU', state: 'Abia', type: 'private' },
  { name: 'Nigerian University of Technology and Management', state: 'Lagos', type: 'private' },
  { name: 'Nile University of Nigeria', state: 'FCT', type: 'private' },
  { name: 'North Eastern University Gombe', state: 'Gombe', type: 'private' },
  { name: 'NorthWest University Sokoto', shortName: 'NWUS', state: 'Sokoto', type: 'private' },
  { name: 'Novena University Ogume', state: 'Delta', type: 'private' },
  { name: 'Obong University Obong Ntak', state: 'Akwa Ibom', type: 'private' },
  { name: 'Oduduwa University Ipetumodu', state: 'Osun', type: 'private' },
  { name: 'Ojaja University Eiyenkorin', state: 'Kwara', type: 'private' },
  { name: 'PAMO University of Medical Sciences Port Harcourt', shortName: 'PUMS', state: 'Rivers', type: 'private' },
  { name: 'Pan-Atlantic University', shortName: 'PAU', state: 'Lagos', type: 'private' },
  { name: 'Paul University Awka', state: 'Anambra', type: 'private' },
  { name: 'PeaceLand University Enugu', state: 'Enugu', type: 'private' },
  { name: 'Peter University Achina-Onneh', state: 'Anambra', type: 'private' },
  { name: 'Philomath University Kuje', state: 'FCT', type: 'private' },
  { name: 'Phoenix University Agwada', state: 'Nasarawa', type: 'private' },
  { name: 'Precious Cornerstone University Oyo', shortName: 'PCU', state: 'Oyo', type: 'private' },
  { name: 'Prime University Kuje', state: 'FCT', type: 'private' },
  { name: 'Rayhaan University Kebbi', state: 'Kebbi', type: 'private' },
  { name: "Redeemer's University Ede", state: 'Osun', type: 'private' },
  { name: 'Renaissance University Enugu', state: 'Enugu', type: 'private' },
  { name: 'Rhema University Obeama-Asa', state: 'Rivers', type: 'private' },
  { name: 'Ritman University Ikot Ekpene', state: 'Akwa Ibom', type: 'private' },
  { name: 'Saisa University of Medical Sciences and Technology', state: 'Sokoto', type: 'private' },
  { name: 'Salem University Lokoja', state: 'Kogi', type: 'private' },
  { name: 'Sam Maris University Ondo', state: 'Ondo', type: 'private' },
  { name: 'Samuel Adegboyega University', state: 'Edo', type: 'private' },
  { name: 'Shanahan University Onitsha', state: 'Anambra', type: 'private' },
  { name: 'Skyline University Kano', shortName: 'SUN', state: 'Kano', type: 'private' },
  { name: 'Southern Atlantic University Uyo', state: 'Akwa Ibom', type: 'private' },
  { name: 'Southwestern University Oku Owa', state: 'Ogun', type: 'private' },
  { name: 'Spiritan University Nneochi', state: 'Abia', type: 'private' },
  { name: 'Sports University Idumuje-Ugboko', state: 'Delta', type: 'private' },
  { name: 'Summit University Offa', state: 'Kwara', type: 'private' },
  { name: 'Tansian University Umunya', state: 'Anambra', type: 'private' },
  { name: 'Tazkiyah University Kaduna', state: 'Kaduna', type: 'private' },
  { name: 'Thomas Adewumi University Oko-Irese', shortName: 'TAU', state: 'Kwara', type: 'private' },
  { name: 'Topfaith University Mkpatak', state: 'Akwa Ibom', type: 'private' },
  { name: 'Trinity University Ogun', state: 'Ogun', type: 'private' },
  { name: 'University of Mkar', state: 'Benue', type: 'private' },
  { name: 'University of Offa', state: 'Kwara', type: 'private' },
  { name: 'University on the Niger Umunya', state: 'Anambra', type: 'private' },
  { name: 'Unique Open University Ojo', state: 'Lagos', type: 'private' },
  { name: 'Venite University Iloro-Ekiti', state: 'Ekiti', type: 'private' },
  { name: 'Veritas University Abuja', state: 'FCT', type: 'private' },
  { name: 'Vision University Ikogbo', state: 'Ogun', type: 'private' },
  { name: 'Wellspring University Evbuobanosa', state: 'Edo', type: 'private' },
  { name: 'Wesley University Ondo', state: 'Ondo', type: 'private' },
  { name: 'West Midlands Open University Ibadan', state: 'Oyo', type: 'private' },
  { name: 'Western Delta University Oghara', state: 'Delta', type: 'private' },
  { name: 'Westland University Iwo', state: 'Osun', type: 'private' },
  { name: 'Wigwe University Isiokpo', state: 'Rivers', type: 'private' },
];
